# =============================================================================
# CAR-PNN configuration (example / documentation)
#
# You normally do NOT edit this file. Run ./configure.sh, which detects what it
# can, asks for the rest, and writes ./config.sh (git-ignored). Every workflow
# script sources config.sh. To configure by hand instead:
#   cp config.example.sh config.sh   # then edit the values below
#
# These are DEFAULTS. A variable already set - hardcoded in a script, or exported in
# your shell - is never overwritten (each line below is "set only if empty").
# Scripts find this file via $CARPNN_CONFIG, else ~/.config/carpnn/config.sh (a link
# ./configure.sh creates; with --no-link, export CARPNN_CONFIG=/path/to/config.sh).
# =============================================================================

# Root of this repository (set automatically by ./configure.sh)
[ -n "${CARPNN_DIR:-}" ] || CARPNN_DIR="/path/to/CARPNN"; export CARPNN_DIR

# --- Boltz workflow (workflows/Boltz) -----------------------------------------
# python in the env created from carpnn.yml          (steps 03, 04, 06, 07, 09, 10)
[ -n "${CARPNN_PYTHON:-}" ] || CARPNN_PYTHON="/path/to/miniconda3/envs/carpnn/bin/python"; export CARPNN_PYTHON
# boltz executable                                   (step 05)
[ -n "${BOLTZ_PATH:-}" ] || BOLTZ_PATH="/path/to/miniconda3/envs/boltz2/bin/boltz"; export BOLTZ_PATH
# ColabFold singularity image and database           (step 02, local MSA search only)
[ -n "${SIF_PATH:-}" ] || SIF_PATH="/path/to/colabfold_1.5.5-cuda12.2.2.sif"; export SIF_PATH
[ -n "${DB_FOLDER:-}" ] || DB_FOLDER="/path/to/colabfold_db"; export DB_FOLDER

# --- BindCraft-style interface scoring (step 08) ------------------------------
# optional: BindCraft checkout, used only to locate DSSP / DAlphaBall below
[ -n "${BINDCRAFT_DIR:-}" ] || BINDCRAFT_DIR="/path/to/BindCraft"; export BINDCRAFT_DIR
# python in an env that has pyrosetta + scipy (e.g. the BindCraft env)
[ -n "${BINDCRAFT_PYTHON:-}" ] || BINDCRAFT_PYTHON="/path/to/miniconda3/envs/BindCraft/bin/python"; export BINDCRAFT_PYTHON
[ -n "${DSSP_PATH:-}" ] || DSSP_PATH="/path/to/BindCraft/functions/dssp"; export DSSP_PATH
[ -n "${DALPHABALL_PATH:-}" ] || DALPHABALL_PATH="/path/to/BindCraft/functions/DAlphaBall.gcc"; export DALPHABALL_PATH

# --- SoluableMPNN (workflows/LigandMPNN) --------------------------------------
[ -n "${LIGANDMPNN_DIR:-}" ] || LIGANDMPNN_DIR="/path/to/CARPNN/public/LigandMPNN"; export LIGANDMPNN_DIR
[ -n "${LIGANDMPNN_PYTHON:-}" ] || LIGANDMPNN_PYTHON="/path/to/miniconda3/envs/ligandmpnn_env/bin/python"; export LIGANDMPNN_PYTHON
[ -n "${CHECKPOINT_PATH:-}" ] || CHECKPOINT_PATH="/path/to/CARPNN/public/LigandMPNN/model_params/solublempnn_v_48_020.pt"; export CHECKPOINT_PATH

# --- AlphaFold single-sequence monomer workflow (workflows/AlphaFold) ---------
[ -n "${RFDAA_AF2_PYTHON:-}" ] || RFDAA_AF2_PYTHON="/path/to/miniconda3/envs/mlfold/bin/python"; export RFDAA_AF2_PYTHON

# --- Slurm (optional) ---------------------------------------------------------
# #SBATCH headers cannot read variables, so these are applied to the scripts by
#   ./configure.sh --set-partitions
[ -n "${SLURM_CPU_PARTITION:-}" ] || SLURM_CPU_PARTITION="cpu"; export SLURM_CPU_PARTITION
[ -n "${SLURM_GPU_PARTITION:-}" ] || SLURM_GPU_PARTITION="gpu"; export SLURM_GPU_PARTITION

true
